# required roles/collections for this role
# ---
# collections:
#   - name: community.windows
# roles:
#   - name: ansible-role-patch-windows
#     src: https://github.com/jeffbildz/ansible-role-patch-windows.git
#     scm: git
#     version: devel
